// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using meoRazor.Data;

#nullable disable

namespace meoRazor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241213094449_AddMigarateCategory")]
    partial class AddMigarateCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("meoRazor.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryID"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("categoryOrder")
                        .HasColumnType("int");

                    b.HasKey("categoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            categoryID = 1,
                            categoryName = "meo",
                            categoryOrder = 1
                        },
                        new
                        {
                            categoryID = 2,
                            categoryName = "neko",
                            categoryOrder = 2
                        },
                        new
                        {
                            categoryID = 3,
                            categoryName = "meoneko",
                            categoryOrder = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
